	org $2000
DISPLAY.DLI
	.BYTE $70,$70,$70	;OTORGAMOS 3 ESPACIOS DE
				;ARRIBA HACIA ABAJO
	.BYTE $46		;OTORGAMOS PRIMER LINEA
				;EN MODO GRAFICO 6
	.WORD LINEA01		;CARGAMOS LINEA01 PARA MOSTRAR
	.BYTE $41		;TERMINAMOS DISPLAY LIST CON 
				;BYTE $41
	.WORD DISPLAY.DLI	;CARGAMOS EL DISPLAY LIST PARA
				;QUE SE ACTIVE
DISPLAY
	LDA #<DISPLAY.DLI
	STA $230
	LDA #>DISPLAY.DLI
	STA $231
	RTS		;OTROGAMOS EL REGRESO
			;DE DONDE SE LLAMO
INICIO
	LDA #80		;CARGAMOS EN EL ACUMULADOR
			;EL VALOR DE 80 COLOR MORADO
	STA 710		;INSERTAMOS EL VALOR 80 EN LA
			;POSICION DE MEMORIA 710 $2C6
			;PARA COLOR DE FONDO PANTALLA
	STA 712		;INSERTAMOS EL VALOR 80 EN LA
			;POSICION DE MEMORIA 712 $2C8
			;PARA CAMBIAR COLOR DE BORDE
	JSR DISPLAY	;LLAMAMOS A LA FUNCION DISPLAY
			;PARA CREAR EL DISPLAY LIST EN
			;PANTALLA DE UNA SOLA LINEA DE
			;20 CARACTERES DE ANCHO
LOOP			;ESTIQUETA LOOP
	JMP LOOP	;GENERAMOS UN LOOP INFINITO
LINEA01
	.BYTE "     HOLA MUNDO     "
	RUN INICIO	;INICIAMOS EL PROGRAMA DESDE
			;INICIO